image: nvcr.io/nvidia/pytorch:24.03-py3

stages:
  - build
  - test

build-job:
  stage: build
  script:
    - pip install -r requirements.txt
    - pip install -e .

lint-test-job:
  stage: test
  script:
    - pip install ruff==0.9.3
    - pip install clang-format==18.1.2
    - ruff check . --output-format github
    - find csrc -name "*.c" -o -name "*.cpp" -o -name "*.h" -o -name "*.hpp"
      -o -name "*.cu" -o -name "*.cuh" | xargs clang-format -style=file --dry-run --Werror
