## https://pre-commit.com/
#
# Before first use: `pre-commit install`
# To run: `pre-commit run --all-files`
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: debug-statements
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.9.3"
    hooks:
      - id: ruff
        args: [--output-format, github, --fix]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.2
    hooks:
      - id: clang-format
        types_or: [c, c++, cuda]
        args: ["-style=file", "-i"]
